

services:
  backend:
    image: esojas/todolist-backend:latest
    restart: always
    environment:
      PORT: 5000
      CONNECTION_URL: mongodb+srv://test:test123@cluster0.1bslu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      REFRESH_TOKEN_SECRET: secret_234
      EMAIL_USER: antoniusjose0126@gmail.com
      EMAIL_PASSWORD: fyzh dgxr yvna tujc
    ports:
      - "3122:3122"

  frontend:
    image: esojas/todolist-frontend:latest
    restart: always
    depends_on:
      - backend
    environment:
      API_URL: http://backend:3122
    ports:
      - "3121:3121"
